import { useEffect, useMemo, useState } from 'react';
import type React from 'react';
import LanguageSwitcher from '../components/LanguageSwitcher';
import { useLanguage } from '../i18n/LanguageContext';

type Copy = { en: string; az: string; tr: string };
type Lang = 'en' | 'az' | 'tr';
const t = (c: Copy, l: Lang) => c[l];
const c = (en: string, az: string, tr: string): Copy => ({ en, az, tr });
const back = c('← Archive', '← Arxiv', '← Arşiv');
const begin = c('Begin', 'Başla', 'Başla');
const restart = c('Play again', 'Yenidən oyna', 'Tekrar oyna');
const ui = {
  setup: c('Setup', 'Quraşdırma', 'Kurulum'), round: c('Round', 'Raund', 'Tur'),
  players: c('Players', 'Oyunçular', 'Oyuncular'), score: c('Score', 'Xal', 'Puan'),
  pause: c('Pause', 'Dayandır', 'Duraklat'), resume: c('Resume', 'Davam et', 'Devam et'),
  end: c('End round', 'Raundu bitir', 'Turu bitir'), submit: c('Submit', 'Göndər', 'Gönder'),
  next: c('Next', 'Növbəti', 'Sonraki'), correct: c('Correct!', 'Doğru!', 'Doğru!'),
  incorrect: c('Not quite', 'Düz deyil', 'Yanlış'), leaderboard: c('Leaderboard', 'Lider cədvəli', 'Liderlik'),
};
function Shell({ children, title, accent, onExit }: { children: React.ReactNode; title: string; accent: string; onExit: () => void }) {
  return <div className="new-game" style={{ '--accent': accent } as React.CSSProperties}><div className="game-top"><span>{title}</span><LanguageSwitcher /></div><main className="game-panel">{children}<button className="quiet-btn" onClick={onExit}>{t(back, useLanguage().lang)}</button></main></div>;
}
function Button({ children, onClick, className = '' }: { children: React.ReactNode; onClick: () => void; className?: string }) { return <button className={`${className || 'primary-btn'}`} onClick={onClick}>{children}</button>; }

const nodes = ['Relay 7', 'Ghost Market', 'Orchid Vault', 'Cobalt Tower', 'The Mesh', 'Null Island', 'Kestrel Lab', 'Black Box'];
const codeText = {
  intro: c('A whistleblower left a route through the city mesh. Eight nodes, one truth.', 'Məlumat verən şəhər şəbəkəsində marşrut qoyub. Səkkiz qovşaq, bir həqiqət.', 'İhbarcı şehir ağında bir rota bıraktı. Sekiz düğüm, tek gerçek.'),
  investigate: c('Investigate node', 'Qovşağı araşdır', 'Düğümü araştır'),
  hack: c('Run bypass puzzle', 'Keçid tapmacasını başlat', 'Atlatma bulmacasını çalıştır'),
  decrypt: c('Decrypt evidence', 'Sübutu deşifrə et', 'Kanıtı çöz'),
};
export function CodeOfShadows({ onExit }: { onExit: () => void }) {
  const { lang } = useLanguage();
  const [screen, setScreen] = useState<'map' | 'node' | 'hack' | 'final' | 'result'>('map');
  const [node, setNode] = useState(0);
  const [trace, setTrace] = useState(18);
  const [solved, setSolved] = useState<string[]>([]);
  const [choice, setChoice] = useState<string | null>(null);
  const [contacts, setContacts] = useState<string[]>([]);
  const [code, setCode] = useState('');
  const [ending, setEnding] = useState('');
  const evidence = solved.length + contacts.length;
  const solve = () => { if (code === '042') { setSolved(s => s.includes(nodes[node]) ? s : [...s, nodes[node]]); setTrace(x => Math.max(0, x - 12)); setScreen('node'); } else setTrace(x => Math.min(100, x + 15)); };
  return <Shell title="CODE//SHADOWS" accent="#ff006e" onExit={onExit}><p className="eyebrow">◈ NIGHT CITY // CASE 07</p>
    {screen === 'map' && <><h1>CODE OF SHADOWS</h1><p className="game-copy">{t(codeText.intro, lang)}</p><div className="trace"><span>TRACE {trace}% · {t(c('EVIDENCE','SÜBUT','KANIT'), lang)} {evidence}/16</span><i style={{ width: `${trace}%` }} /></div><div className="shadow-map">{nodes.map((n, i) => <button className={`map-node ${solved.includes(n) ? 'cleared' : ''}`} key={n} onClick={() => { setNode(i); setScreen('node'); }}>{i + 1}<small>{n}</small></button>)}</div><div className="card-row"><div className="data-card">⌁ {t(c('Evidence cards', 'Sübut kartları', 'Kanıt kartları'), lang)}<b>{solved.length}</b></div><div className="data-card">◎ {t(c('Contact trust', 'Əlaqə etibarı', 'Bağlantı güveni'), lang)}    <b>{contacts.length}/8</b></div></div><Button onClick={() => setScreen('final')}>{t(c('Open case file', 'İş faylını aç', 'Dosyayı aç'), lang)}</Button></>}
    {screen === 'node' && <><p className="eyebrow">NODE {node + 1} / 8</p><h1>{nodes[node]}</h1><p className="game-copy">{t(c('Camera feeds flicker. A locked terminal contains an encrypted fragment.', 'Kamera görüntüləri titrəyir. Kilidli terminalda şifrəli parça var.', 'Kamera yayınları titriyor. Kilitli terminalda şifreli bir parça var.'), lang)}</p><div className="choice-grid"><Button onClick={() => setScreen('hack')}>{t(codeText.hack, lang)}</Button><Button onClick={() => { setContacts(x => x.includes(`Mira-${node}`) ? x : [...x, `Mira-${node}`]); setTrace(x => Math.min(100, x + 8)); }}>{t(c('Call Mira (trust +1)', 'Mira ilə əlaqə saxla (etibar +1)', 'Mira’yı ara (güven +1)'), lang)}</Button><Button onClick={() => { setSolved(s => s.includes(nodes[node]) ? s : [...s, nodes[node]]); setScreen('map'); }}>{t(c('Capture camera evidence', 'Kamera sübutunu saxla', 'Kamera kanıtını al'), lang)}</Button><Button onClick={() => setScreen('map')}>{t(c('Return to map', 'Xəritəyə qayıt', 'Haritaya dön'), lang)}</Button></div></>}
    {screen === 'hack' && <><p className="eyebrow">TERMINAL // CAMERA BYPASS</p><h1>{t(c('Find the three-digit key', 'Üç rəqəmli açarı tap', 'Üç haneli anahtarı bul'), lang)}</h1><p className="game-copy">{t(c('The hint is 0 × 4 + 2. Enter the result to decrypt the shard.', 'İpucu 0 × 4 + 2-dir. Parçanı açmaq üçün nəticəni daxil et.', 'İpucu 0 × 4 + 2. Parçayı çözmek için sonucu gir.'), lang)}</p><input aria-label={t(c('Three-digit bypass key','Üç rəqəmli keçid açarı','Üç haneli geçiş anahtarı'),lang)} className="code-input" name="bypass-key" autoComplete="one-time-code" inputMode="numeric" value={code} onChange={e => setCode(e.target.value)} maxLength={3} placeholder="000" /><Button onClick={solve}>{t(codeText.decrypt, lang)}</Button><p className="trace">{t(c('Wrong attempts raise detection.', 'Səhv cəhdlər aşkarlanmanı artırır.', 'Yanlış denemeler tespiti artırır.'), lang)}</p></>}
    {screen === 'final' && <><p className="eyebrow">CASE FILE // LEAK THE TRUTH</p><h1>{t(c('What will you leak?', 'Nəyi sızdıracaqsan?', 'Neyi sızdıracaksın?'), lang)}</h1><div className="choice-grid">{['Data archive', 'Camera proof', 'Nothing'].map(x => <Button key={x} onClick={() => setChoice(x)} className={choice === x ? 'primary-btn selected' : 'choice-grid button'}>{x}</Button>)}</div>{choice && <><p className="game-copy">{t(c('Choose a recipient and method. Every path has a cost.', 'Qəbul edəni və üsulu seç. Hər yolun bədəli var.', 'Alıcıyı ve yöntemi seç. Her yolun bedeli var.'), lang)}</p><div className="choice-grid"><Button onClick={() => { setEnding(`${choice} → public broadcast`); setScreen('result'); }}>Public broadcast</Button><Button onClick={() => { setEnding(`${choice} → trusted journalist`); setScreen('result'); }}>Trusted journalist</Button><Button onClick={() => { setEnding(`${choice} → Mira network`); setScreen('result'); }}>Mira’s network</Button></div></>}</>}
    {screen === 'result' && <><p className="eyebrow">EXTRACTION COMPLETE</p><h1>{ending.includes('public') ? 'THE TRUTH IS LOUD' : ending.includes('journalist') ? 'THE STORY SURVIVES' : 'GHOST PROTOCOL'}</h1><p className="game-copy">{t(c(`You recovered ${evidence} evidence cards. Detection ended at ${trace}%.`, `${evidence} sübut kartı topladın. Aşkarlanma ${trace}%-də dayandı.`, `${evidence} kanıt kartı topladın. Tespit ${trace}%'te durdu.`), lang)}</p><Button onClick={() => { setScreen('map'); setSolved([]); setTrace(18); setChoice(null); }}>{t(restart, lang)}</Button></>}
  </Shell>;
}

const spyLocations = ['Harbor Hotel','Old Cinema','Train Depot','Embassy Garden','Night Market','Mountain Relay','Museum Annex','Rooftop Bar','University Lab','Desert Camp','Clock Tower','Canal Lock','Radio Ship','Winter Lodge','Opera House','Solar Farm','Ferry Terminal','Archive Basement','Botanical Dome','Airfield Hangar'];
export function SpyRing({ onExit }: { onExit: () => void }) {
  const { lang } = useLanguage(); const [phase, setPhase] = useState<'setup'|'roles'|'discussion'|'vote'|'guess'|'result'|'debrief'>('setup'); const [count, setCount] = useState(3); const [names, setNames] = useState(['Player 1','Player 2','Player 3']); const [turn, setTurn] = useState(0); const [revealed, setRevealed] = useState(false); const [spy, setSpy] = useState(0); const [location, setLocation] = useState(''); const [votes, setVotes] = useState<number[]>([]); const [voteTurn, setVoteTurn] = useState(0); const [timer, setTimer] = useState(300); const [paused, setPaused] = useState(false); const [guess, setGuess] = useState(''); const [scores, setScores] = useState<number[]>([0,0,0,0,0]);
  useEffect(() => { if (phase !== 'discussion' || paused || timer <= 0) return; const id = window.setInterval(() => setTimer(x => x - 1), 1000); return () => window.clearInterval(id); }, [phase, paused, timer]);
  const start = () => { setNames(n => Array.from({length: count}, (_, i) => n[i] || `Player ${i+1}`)); setSpy(Math.floor(Math.random()*count)); setLocation(spyLocations[Math.floor(Math.random()*spyLocations.length)]); setTurn(0); setVoteTurn(0); setVotes([]); setRevealed(false); setPhase('roles'); };
  const finishVote = (i: number) => { const next = [...votes, i]; setVotes(next); if (voteTurn + 1 >= count) setPhase('guess'); else setVoteTurn(v => v + 1); };
  return <Shell title="OPERATION: RAVEN" accent="#d4af5a" onExit={onExit}><p className="eyebrow">CLASSIFIED // PASS DEVICE</p>
    {phase === 'setup' && <><h1>{t(c('THE SPY RING','CASUS ŞƏBƏKƏSİ','CASUS HALKASI'),lang)}</h1><p className="game-copy">{t(c('Set 3–5 names, choose a 5–8 minute discussion, then pass the device.', '3–5 ad yaz, 5–8 dəqiqəlik müzakirə seç və cihazı ötür.', '3–5 isim yaz, 5–8 dakikalık tartışma seç ve cihazı devret.'),lang)}</p><div className="name-grid">{Array.from({length:count},(_,i)=><input aria-label={`${t(ui.players,lang)} ${i+1}`} name={`spy-player-${i+1}`} autoComplete="off" key={i} value={names[i]||''} onChange={e=>setNames(n=>n.map((x,j)=>j===i?e.target.value:x))} />)}</div><div className="number-picker">{[3,4,5].map(n=><Button key={n} className={count===n?'number-picker button selected':'number-picker button'} onClick={()=>{setCount(n);setNames(Array.from({length:n},(_,i)=>names[i]||`Player ${i+1}`))}}>{n}</Button>)}</div><label>{t(c('Minutes','Dəqiqə','Dakika'),lang)} <input aria-label={t(c('Discussion minutes','Müzakirə dəqiqələri','Tartışma dakikası'),lang)} name="discussion-minutes" autoComplete="off" type="number" min="5" max="8" value={Math.round(timer/60)} onChange={e=>setTimer(Math.max(300,Math.min(480,Number(e.target.value)*60)))} /></label><br/><Button onClick={start}>{t(begin,lang)}</Button></>}
    {phase === 'roles' && <><h1>{names[turn]}</h1>{!revealed?<Button onClick={()=>setRevealed(true)}>{t(c('Hold to reveal dossier','Dosyeni görmək üçün basılı saxla','Dosyayı görmek için basılı tut'),lang)}</Button>:<><div className={`dossier ${turn===spy?'mole':''}`}>{turn===spy?t(c('You are the SPY','Sən CASUSSAN','Sen CASUSSUN'),lang):<>{t(c('Location','Məkan','Konum'),lang)}: <b>{location}</b></>}</div><Button onClick={()=>{setRevealed(false);if(turn+1===count)setPhase('discussion');else setTurn(turn+1)}}>{turn+1===count?t(ui.next,lang):t(c('Pass device','Cihazı ötür','Cihazı devret'),lang)}</Button></>}</>}
    {phase === 'discussion' && <><h1>{t(c('Discuss the clues','İpuclarını müzakirə et','İpuçlarını tartış'),lang)}</h1><div className="timer">{String(Math.floor(timer/60)).padStart(2,'0')}:{String(timer%60).padStart(2,'0')}</div><Button onClick={()=>setPaused(x=>!x)}>{t(paused?ui.resume:ui.pause,lang)}</Button><Button onClick={()=>setPhase('vote')}>{t(ui.end,lang)}</Button></>}
    {phase === 'vote' && <><h1>{names[voteTurn]} · {t(c('Vote for the spy','Casusu seç','Casusu seç'),lang)}</h1><div className="vote-list">{names.map((n,i)=><Button key={n} onClick={()=>finishVote(i)}>{n}</Button>)}</div><p>{t(c('Votes cast','Verilən səslər','Verilen oylar'),lang)}: {votes.length}/{count}</p></>}
    {phase === 'guess' && <><h1>{names[spy]}: {t(c('Spy, guess the location','Casus, məkanı təxmin et','Casus, konumu tahmin et'),lang)}</h1><select aria-label={t(c('Spy location guess','Casusun məkan təxmini','Casusun konum tahmini'),lang)} name="spy-location" autoComplete="off" value={guess} onChange={e=>setGuess(e.target.value)}><option value="">—</option>{spyLocations.map(x=><option key={x}>{x}</option>)}</select><Button onClick={()=>{setPhase('result');setScores(s=>s.map((x,i)=>x+(votes[0]===spy?i===spy?0:2:i===spy?3:0)+(guess===location&&i===spy?2:0)))}}>{t(ui.submit,lang)}</Button></>}
    {phase === 'result' && <><h1>{t((votes.filter(v=>v===spy).length > Math.floor(count/2)) ? c('The ring exposed the spy','Şəbəkə casusu ifşa etdi','Halka casusu açığa çıxardı') : c('The spy escaped','Casus qaçdı','Casus kaçtı'),lang)}</h1><p className="game-copy">{names.map((n,i)=>`${n}: ${votes.filter(v=>v===i).length}`).join(' · ')} · {location} · {guess===location?t(ui.correct,lang):t(ui.incorrect,lang)}</p><Button onClick={()=>setPhase('debrief')}>{t(ui.leaderboard,lang)}</Button></>}
    {phase === 'debrief' && <><h1>{t(c('Debrief','Debrifinq','Bilgilendirme'),lang)}</h1><div className="scoreboard">{names.map((n,i)=><div key={n}>{n}<b>{scores[i]||0}</b></div>)}</div><Button onClick={()=>setPhase('setup')}>{t(restart,lang)}</Button></>}
  </Shell>;
}

type Question = { category: string; q: Copy; options: Copy[]; answer: number };
const categories = ['History','Science','Pop Culture','Geography','Sports','Movies'];
const categoryLabels: Record<string, Copy> = {
  History: c('History', 'Tarix', 'Tarih'), Science: c('Science', 'Elm', 'Bilim'),
  'Pop Culture': c('Pop Culture', 'Populyar mədəniyyət', 'Popüler kültür'),
  Geography: c('Geography', 'Coğrafiya', 'Coğrafya'), Sports: c('Sports', 'İdman', 'Spor'),
  Movies: c('Movies', 'Filmlər', 'Filmler'),
};
const questionData: Record<string, [string, string[], number][]> = {
  History: [['Who was the first US president?',['Washington','Lincoln','Jefferson'],0],['Which empire built Machu Picchu?',['Inca','Roman','Ottoman'],0],['The Magna Carta was signed in which country?',['England','France','Spain'],0],['Who was Cleopatra?',['Egyptian queen','Roman poet','Greek general'],0],['The Renaissance began in which country?',['Italy','Norway','Mexico'],0],['Which city was ancient Troy near?',['Turkey','Ireland','Canada'],0],['Who led India’s nonviolent independence movement?',['Gandhi','Mandela','Churchill'],0],['The Berlin Wall fell in which decade?',['1980s','1960s','2000s'],0]],
  Science: [['What gas do plants absorb?',['Carbon dioxide','Oxygen','Helium'],0],['What is H2O?',['Water','Salt','Hydrogen'],0],['Which organ pumps blood?',['Heart','Liver','Lung'],0],['What is the speed of light measured in?',['Meters per second','Liters','Newtons'],0],['Which particle has a negative charge?',['Electron','Proton','Neutron'],0],['What is the closest star to Earth?',['Sun','Sirius','Polaris'],0],['Which vitamin comes from sunlight?',['Vitamin D','Vitamin C','Vitamin B12'],0],['What process makes plants use sunlight?',['Photosynthesis','Fermentation','Evaporation'],0]],
  'Pop Culture': [['Which wizard attends Hogwarts?',['Harry Potter','Luke Skywalker','Frodo'],0],['What is Pikachu?',['A Pokémon','A robot','A dragon'],0],['Which singer released Thriller?',['Michael Jackson','Prince','Elton John'],0],['What is the fictional city of Gotham linked to?',['Batman','Superman','Wonder Woman'],0],['Which game features a battle royale island?',['Fortnite','Tetris','Chess'],0],['Which platform is known for short videos?',['TikTok','LinkedIn','Wikipedia'],0],['What color is Shrek?',['Green','Blue','Purple'],0],['Which band recorded Yellow Submarine?',['The Beatles','ABBA','Queen'],0]],
  Geography: [['What is the largest continent?',['Asia','Africa','Europe'],0],['Which country has the Sahara?',['Africa','Brazil','Japan'],0],['What is the capital of Japan?',['Tokyo','Kyoto','Osaka'],0],['Which ocean borders California?',['Pacific','Atlantic','Indian'],0],['Mount Everest is in which range?',['Himalayas','Alps','Andes'],0],['Which country is shaped like a boot?',['Italy','India','Chile'],0],['What is the smallest continent?',['Australia','Europe','Antarctica'],0],['The Nile flows into which sea?',['Mediterranean','Red Sea','Baltic'],0]],
  Sports: [['How many rings are on the Olympic flag?',['Five','Four','Six'],0],['Which sport uses a puck?',['Ice hockey','Tennis','Cricket'],0],['How long is a marathon?',['42.195 km','10 km','100 km'],0],['What is a birdie in?',['Badminton','Football','Boxing'],0],['Which country hosts sumo tradition?',['Japan','Brazil','Egypt'],0],['What is love in tennis scoring?',['Zero','One','Forty'],0],['How many bases in baseball?',['Four','Three','Five'],0],['Which sport has a scrum?',['Rugby','Golf','Swimming'],0]],
  Movies: [['Who directed E.T.?',['Steven Spielberg','James Cameron','Greta Gerwig'],0],['Which film features a DeLorean?',['Back to the Future','Jaws','Alien'],0],['What is Pixar’s lamp called?',['Luxo','Robo','Luma'],0],['Which movie has the line “I’ll be back”?',['Terminator','Titanic','Casablanca'],0],['Who played Jack in Titanic?',['Leonardo DiCaprio','Tom Hanks','Brad Pitt'],0],['Which genre is Parasite?',['Thriller','Western','Musical'],0],['What does a director shout to begin?',['Action','Cut','Roll'],0],['Which film features Wakanda?',['Black Panther','Avatar','Rocky'],0]],
};
const questionTranslations: Record<string, Copy[]> = {
  History: ['Birinci ABŞ prezidenti kim idi?', 'Machu Picchu hansı imperiyaya məxsusdur?', 'Magna Carta hansı ölkədə imzalanıb?', 'Kleopatra kim idi?', 'İntibah hansı ölkədə başladı?', 'Qədim Troya hansı ölkənin yaxınlığında idi?', 'Hindistanın müstəqillik hərəkatına kim rəhbərlik etdi?', 'Berlin divarı hansı onillikdə yıxıldı?'].map((az, i) => c(questionData.History[i][0], az, ['ABD’nin ilk başkanı kimdi?','Machu Picchu hangi imparatorluğa aitti?','Magna Carta hangi ülkede imzalandı?','Kleopatra kimdi?','Rönesans hangi ülkede başladı?','Antik Truva hangi ülkeye yakındı?','Hindistan bağımsızlık hareketine kim öncülük etti?','Berlin Duvarı hangi on yılda yıkıldı?'][i])),
  Science: ['Bitkilər hansı qazı udur?', 'H2O nədir?', 'Hansı orqan qanı pompalayır?', 'İşıq sürəti nə ilə ölçülür?', 'Mənfi yüklü hissəcik hansıdır?', 'Yerə ən yaxın ulduz hansıdır?', 'Günəş işığından hansı vitamin alınır?', 'Bitkilər günəş işığını hansı proseslə istifadə edir?'].map((az, i) => c(questionData.Science[i][0], az, ['Bitkiler hangi gazı emer?','H2O nedir?','Hangi organ kanı pompalar?','Işık hızı neyle ölçülür?','Negatif yüklü parçacık hangisi?','Dünya’ya en yakın yıldız hangisi?','Güneş ışığından hangi vitamin alınır?','Bitkiler güneş ışığını hangi süreçte kullanır?'][i])),
  'Pop Culture': ['Hogwartsda hansı sehrbaz oxuyur?', 'Pikachu nədir?', 'Thriller albomunu hansı müğənni buraxıb?', 'Qotem şəhəri hansı qəhrəmanla bağlıdır?', 'Hansı oyunda ada döyüşü var?', 'Qısa videolarla tanınan platforma hansıdır?', 'Şrek hansı rəngdədir?', 'Yellow Submarine mahnısını hansı qrup yazıb?'].map((az, i) => c(questionData['Pop Culture'][i][0], az, ['Hogwarts’a hangi büyücü gider?','Pikachu nedir?','Thriller albümünü hangi şarkıcı çıkardı?','Gotham hangi kahramanla bağlantılıdır?','Hangi oyunda ada savaşı vardır?','Kısa videolarıyla bilinen platform hangisi?','Shrek ne renktir?','Yellow Submarine’i hangi grup kaydetti?'][i])),
  Geography: ['Ən böyük qitə hansıdır?', 'Sahara hansı qitədədir?', 'Yaponiyanın paytaxtı hansıdır?', 'Kaliforniya hansı okeanla həmsərhəddir?', 'Everest hansı dağ silsiləsindədir?', 'Çəkmə formasında olan ölkə hansıdır?', 'Ən kiçik qitə hansıdır?', 'Nil hansı dənizə tökülür?'].map((az, i) => c(questionData.Geography[i][0], az, ['Welcher ist der größte Kontinent?','Auf welchem Kontinent liegt die Sahara?','Was ist die Hauptstadt Japans?','Welcher Ozean grenzt an Kalifornien?','In welchem Gebirge liegt der Everest?','Welches Land ist stiefelförmig?','Welcher ist der kleinste Kontinent?','In welches Meer mündet der Nil?'][i])),
  Sports: ['Olimpiya bayrağında neçə halqa var?', 'Şayba hansı idmanda istifadə olunur?', 'Marafonun məsafəsi nə qədərdir?', 'Badminton oyununda “birdie” nədir?', 'Sumo ənənəsi hansı ölkəyə aiddir?', 'Tennisdə “love” neçə xaldır?', 'Beysbolun neçə bazası var?', 'Skrum hansı idmandadır?'].map((az, i) => c(questionData.Sports[i][0], az, ['Wie viele Ringe hat die Olympische Flagge?','Welche Sportart benutzt einen Puck?','Wie lang ist ein Marathon?','Was ist ein Birdie?','Welches Land hat die Sumo-Tradition?','Was bedeutet Love im Tennis?','Wie viele Bases gibt es im Baseball?','In welcher Sportart gibt es ein Scrum?'][i])),
  Movies: ['E.T. filmini kim çəkib?', 'DeLorean hansı filmdədir?', 'Pixar lampasının adı nədir?', '“Qayıdacağam” replikası hansı filmdədir?', 'Titanikdə Ceki kim oynayıb?', 'Parasite hansı janrdadır?', 'Rejissor çəkilişə başlamaq üçün nə deyir?', 'Vakanda hansı filmdədir?'].map((az, i) => c(questionData.Movies[i][0], az, ['Wer führte Regie bei E.T.?','In welchem Film gibt es einen DeLorean?','Wie heißt Pixars Lampe?','In welchem Film fällt der Satz „Ich komme zurück“?','Wer spielte Jack in Titanic?','Welches Genre hat Parasite?','Was ruft ein Regisseur zum Beginn?','In welchem Film gibt es Wakanda?'][i])),
};
const optionTranslations: Record<string, Copy> = {
  Washington: c('Washington','Vaşinqton','Washington'), Lincoln: c('Lincoln','Linkoln','Lincoln'), Jefferson: c('Jefferson','Cefferson','Jefferson'),
  England: c('England','İngiltərə','İngiltere'), France: c('France','Fransa','Fransa'), Spain: c('Spain','İspaniya','İspanya'),
  'Carbon dioxide': c('Carbon dioxide','Karbon qazı','Karbondioksit'), Oxygen: c('Oxygen','Oksigen','Oksijen'), Helium: c('Helium','Helium','Helyum'),
  Water: c('Water','Su','Su'), Salt: c('Salt','Duz','Tuz'), Hydrogen: c('Hydrogen','Hidrogen','Hidrojen'),
  Heart: c('Heart','Ürək','Kalp'), Liver: c('Liver','Qaraciyər','Karaciğer'), Lung: c('Lung','Ağciyər','Akciğer'),
};
const questions = categories.flatMap(category => questionData[category].map(([question, options, answer], i) => ({ category, q: questionTranslations[category][i], options: options.map(x => optionTranslations[x] ?? c(x, x, x)), answer })));
export function TriviaThrone({ onExit }: { onExit: () => void }) {
  const {lang}=useLanguage(); const [phase,setPhase]=useState<'setup'|'wheel'|'play'|'result'>('setup'); const [count,setCount]=useState(3); const [names,setNames]=useState(['Player 1','Player 2','Player 3']); const [rounds,setRounds]=useState(8); const [q,setQ]=useState(0); const [turn,setTurn]=useState(0); const [scores,setScores]=useState([0,0,0,0,0]); const [locked,setLocked]=useState(false); const [buzzed,setBuzzed]=useState<number|null>(null); const [feedback,setFeedback]=useState(''); const [category,setCategory]=useState(categories[0]); const [powers,setPowers]=useState(names.map(()=>({double:true,steal:true,skip:true})));
  const categoryQuestions=questions.filter(item=>item.category===category); const current=categoryQuestions[q % categoryQuestions.length] ?? questions[0]; const ranking=useMemo(()=>names.slice(0,count).map((name,i)=>({name,score:scores[i]||0})).sort((a,b)=>b.score-a.score),[names,count,scores]);
  const resolve=(ok:boolean, points=1)=>{if(locked || buzzed===null)return;setLocked(true);setFeedback(ok?t(ui.correct,lang):t(ui.incorrect,lang));if(ok)setScores(s=>s.map((x,j)=>j===buzzed?x+points:x));setTimeout(()=>{setFeedback('');setLocked(false);setBuzzed(null);if(q+1>=rounds)setPhase('result');else{setQ(x=>(x+1)%categoryQuestions.length);setTurn(x=>(x+1)%count)}},700)};
  const usePower=(kind:'double'|'steal'|'skip')=>{if(powers[turn]?.[kind]===false || locked)return;setPowers(ps=>ps.map((p,i)=>i===turn?{...p,[kind]:false}:p));if(kind==='double')resolve(true,2);else if(kind==='skip'){setBuzzed(turn);resolve(false,0);}else setBuzzed(turn)};
  return <Shell title="THE GRAND QUIZ" accent="#b06fff" onExit={onExit}><p className="eyebrow">♛ ROYAL ARENA</p>
    {phase==='setup'&&<><h1>{t(c('TRIVIA THRONE','BİLİK TA XTI','BİLGİ TAHTI'),lang)}</h1><p className="game-copy">{t(c('Choose a category, 3–5 players and the number of rounds.', 'Kateqoriya, 3–5 oyunçu və raund sayını seç.', 'Kategori, 3–5 oyuncu ve tur sayısını seç.'),lang)}</p><div className="name-grid">{Array.from({length:count},(_,i)=><input aria-label={`${t(ui.players,lang)} ${i+1}`} name={`trivia-player-${i+1}`} autoComplete="off" key={i} value={names[i]||''} onChange={e=>setNames(n=>n.map((x,j)=>j===i?e.target.value:x))}/>)}</div><div className="category-grid">{categories.map(x=><button aria-label={t(categoryLabels[x],lang)} key={x} className={category===x?'selected':''} onClick={()=>setCategory(x)}>{t(categoryLabels[x],lang)}</button>)}</div><label>{t(c('Rounds','Raundlar','Turlar'),lang)} <input aria-label={t(c('Number of rounds','Raund sayı','Tur sayısı'),lang)} name="trivia-rounds" autoComplete="off" type="number" min="6" max="24" value={rounds} onChange={e=>setRounds(Number(e.target.value))}/></label><br/><Button onClick={()=>{setQ(0);setPhase('wheel')}}>{t(begin,lang)}</Button></>}
    {phase==='wheel'&&<><h1 className="wheel">◉</h1><p className="game-copy">{t(c('The category wheel is spinning…','Kateqoriya çarxı fırlanır…','Kategori çarkı dönüyor…'),lang)}</p><Button onClick={()=>setPhase('play')}>{t(ui.next,lang)}</Button></>}
    {phase==='play'&&<><p className="eyebrow">{q+1}/{rounds} · {t(categoryLabels[current.category],lang)}</p><h1>{t(current.q,lang)}</h1><p>{feedback}</p>{buzzed===null?<><p className="game-copy">{t(c('Shared host device: first player to buzz owns the answer.', 'Ortaq host cihazı: ilk basan oyunçu cavab hüququnu alır.', 'Ortak host cihazı: ilk basan oyuncu cevap hakkını alır.'),lang)}</p><Button onClick={()=>setBuzzed(turn)}>{t(c(`${names[turn]} BUZZ`,`${names[turn]} BASIR`,`${names[turn]} BASIYOR`),lang)}</Button></>:<div className="choice-grid"><p>{names[buzzed]} · {t(c('Host: mark the answer','Host: cavabı qiymətləndir','Host: cevabı değerlendir'),lang)}</p><Button onClick={()=>resolve(true)}>{t(ui.correct,lang)}</Button><Button onClick={()=>resolve(false)}>{t(ui.incorrect,lang)}</Button></div>}<div className="powerups"><Button onClick={()=>usePower('double')}>DOUBLE {powers[turn]?.double?'●':'○'}</Button><Button onClick={()=>usePower('steal')}>STEAL {powers[turn]?.steal?'●':'○'}</Button><Button onClick={()=>usePower('skip')}>SKIP {powers[turn]?.skip?'●':'○'}</Button></div><div className="score-strip">{ranking.map(x=><span key={x.name}>{x.name}: {x.score}</span>)}</div></>}
    {phase==='result'&&<><h1>♛ {ranking[0]?.name}</h1><p className="game-copy">{t(c('Final stats recap','Yekun statistika','Final istatistikler'),lang)}</p><div className="scoreboard">{ranking.map(x=><div key={x.name}>{x.name}<b>{x.score}</b></div>)}</div><Button onClick={()=>setPhase('setup')}>{t(restart,lang)}</Button></>}
  </Shell>;
}
